# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: report.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "report.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0creport.proto"4\n\rReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nyear_month\x18\x02 \x01(\t"#\n\x0eReportResponse\x12\x11\n\treport_id\x18\x01 \x01(\t2@\n\rReportService\x12/\n\x0c\x43reateReport\x12\x0e.ReportRequest\x1a\x0f.ReportResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "report_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REPORTREQUEST"]._serialized_start = 16
    _globals["_REPORTREQUEST"]._serialized_end = 68
    _globals["_REPORTRESPONSE"]._serialized_start = 70
    _globals["_REPORTRESPONSE"]._serialized_end = 105
    _globals["_REPORTSERVICE"]._serialized_start = 107
    _globals["_REPORTSERVICE"]._serialized_end = 171
# @@protoc_insertion_point(module_scope)
